name: fl_server_driven
description: "A new Flutter project."


version: 0.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  json_dynamic_widget_codegen: ^1.0.6
  json_dynamic_widget_plugin_components: ^1.0.1
  json_dynamic_widget_plugin_font_awesome: ^4.0.0+24
  json_dynamic_widget_plugin_ionicons: ^4.0.0+28
  json_dynamic_widget_plugin_js: ^2.0.2+20
  json_dynamic_widget_plugin_lottie: ^4.0.0+23
  json_dynamic_widget_plugin_material_icons: ^4.0.0+24
  json_dynamic_widget_plugin_markdown: ^5.0.0+16
  json_dynamic_widget_plugin_rive: ^4.0.0+15
  json_dynamic_widget_plugin_svg: ^4.0.0+25
  flutter_modular: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

